### ISSUE TITLE
A /chat page

### ISSUE THREAD

**Issue by AnthonyRonning** [BitcoinDevShop/mutiny-website#1]
For some reason, people on iOS seem to have a hard time joining the Mutiny matrix space. Does not seem specific to Mutiny's, I had them test other spaces as well. Works on android and desktop. 

I don't want to liter the frontpage with "join our chat (but use this link if you're an ios cuck)" so maybe a /chat page based on the index.html that tells them that? Just some thoughts, can also specifically link to /chat when saying how people can reach us and can also put some more info there later in the future too.

**Comment by mission-bitcoin** [comment]
PR submitted!

**Comment by AnthonyRonning** [comment]
I merged it and tested it out when it deployed. For some reason it did not load any of the /chat or /resources pages. It was getting a 404 on it. So I reverted the change. 

I'm not sure if it's something on how it was deployed or what. Do you have any insights into it @futurepaul ? https://github.com/BitcoinDevShop/mutiny-website/pull/2

**Comment by mission-bitcoin** [comment]
The new PR for this should work now - I needed to add the new assets (back_icon.png, resources.html, chat.html) to the copy line in the Docker file.
